apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cyclegan-trainer-cntk
  name: cyclegan-trainer-cntk
spec:
  template:
    metadata:
      name: cyclegan-trainer-cntk
    spec:
      volumes:
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      - name: azurefile
        azureFile:
            secretName: azure-secret
            shareName: data
            readOnly: false      
      containers:
      - name: cyclegan-trainer-cntk
        command: ["/bin/bash", "-c"]
        args: ["source '/cntk/activate-cntk'; export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/mpi/lib:/usr/lib/x86_64-linux-gnu_custom:/usr/lib/x86_64-linux-gnu; echo $LD_LIBRARY_PATH; python trainDCGan.py;"]
        image: ritazh/cyclegan-cntk
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/lib/x86_64-linux-gnu_custom
          name: libraries
        - mountPath: "/data"
          name: azurefile
        imagePullPolicy: Always
        env:
        - name: MOVE_DATA_REMOTE
          value: '1'
        - name: MOVE_DATA_LOCALLY
          value: '0'    
      restartPolicy: Never
